### ISSUE TITLE
¿Sólo para presidencia?

### ISSUE THREAD

**Issue by martinszy** [argob/poncho#1]
Hola, quería saber si este framework buscar ser sólo para los sitios de presidencia o para todos los sitios de la APN.
¿Buscan difundirlo a otros equipos?

**Comment by julianrod** [comment]
La idea es extender su uso hacia toda la Administración Pública. Todavía de manera no obligatoria.

**Comment by martinszy** [comment]
Gracias por la respuesta. Siendo que es no obligatorio, sino voluntario ¿Cómo esperan extender el uso a otros equipos?

**Comment by julianrod** [comment]
En general, con capacitaciones, workshops, estándares obligatorios y consultorías.
Vemos una enorme predisposición por parte de todas las áreas con las que ya hablamos para usar nuestro framework.

**Comment by martinszy** [comment]
Cómo se los contacta para solicitar una capacitación?

**Comment by vlasvlasvlas** [comment]
Hola, +1 a tutorial / workshop / webinar para difundir Poncho!

**Comment by julianrod** [comment]
Nos pueden escribir a serviciosdigitales@modernizacion.gob.ar
