### ISSUE TITLE
Tamaño de texto en dropdown

### ISSUE THREAD

**Issue by mechafiz** [argob/poncho#10]
En la página de poncho (http://argob.github.io/poncho/), en el header el tamaño de textos de las secciones (caso sección "ejemplos") es de 15px, mientras que los textos dentro de su dropdown son de 16px. No debería ser más grande el texto de la sección (osea el padre) y más chico el texto dentro de él (sus hijos). O tal vez, como en el caso de Casa Rosada (http://www.casarosada.gob.ar/) donde los textos tiene el mismo tamaño 16px, pero cambia el font-weight.

**Comment by Jinik** [comment]
En este caso, el tamaño de tipografía en la navegación se achica para que puedan entrar más elementos sin tener que ocultarlos en un menú desplegable. El desplegable sigue con el texto del mismo tamaño porque no hay necesidad de espacio para achicarlos.
