### ISSUE TITLE
bg-gray y bg-white no tienen !important

### ISSUE THREAD

**Issue by fgoni** [argob/poncho#15]
Entendiendo que las clases helpers son para cambiar un solo aspecto de un elemento y que deberían overridear el aspecto default, no veo la razón de que bg-gray y bg-white no tengan !important, cuando todos los otros colores si la tienen.

Seguramente hay alguna decisión técnica o de diseño que no estoy viendo.

Saludos!

**Comment by Roccella** [comment]
Gracias por tu colaboración! Ya lo corregimos

2016-11-02 18:43 GMT-03:00 Facundo Goñi <notifications@github.com>:
