### ISSUE TITLE
Reglas css extrañas

### ISSUE THREAD

**Issue by levihernan** [argob/poncho#19]
.article {
 margin-top: -30px !important
}
//Mueve 30px indeseados un article dentro del WordPress de Producción que está implementando Poncho

@media (max-width: 420px)
poncho.css:1187
.navbar .container .navbar-header .navbar-brand img {
    width: 115%;
    max-width: none;
}
//Ensancha el logo para mobile devices

**Comment by diegoarduino** [comment]
Gracias por tu colaboración @levihernan. 
Lo de logo ya está corregido.
Con respecto a esto:
.article {
margin-top: -30px !important
}
No se encuentra esa regla de estilo, por favor especificar.
