### ISSUE TITLE
Alertas

### ISSUE THREAD

**Issue by martinszy** [argob/poncho#2]
Hola, veo que en la documentación, en la parte de "alerts" están las alertas por default de bootstrap y otras dos cosas que son ejemplos nuevos, que no entran en la categoría de alertas, son como banners o destacados que se parecen bastante a una alerta pero cumplen otra función, o no?
https://argob.github.io/poncho/docs/#components

Creo que las alertas de bootstrap sirven para anunciar algo que acaba de ocurrir, van normalmente arriba de todo en la página.
En cambio estos banners son contenidos destacados para promover acciones por parte del usuario.

Sugiero ponerlos en una categoría diferente.

**Comment by Jinik** [comment]
Hola @martinszy,
De la manera que estamos encarando la documentación en esta etapa, explicamos los complementos y cómo estéticamente se modifican por medio del código.

Los elementos que armamos no tienen específicamente un solo uso.
En la última actualización de la documentación los separamos como alertas y alertas con icono, porque desde el html eso es lo que son.

Gracias por sugerencia.
