### ISSUE TITLE
Botón sobre bg-primary tiene texto ilegible

### ISSUE THREAD

**Issue by levihernan** [argob/poncho#21]
Si desplegamos un botón sobre una sección de fondo azul (bg-primary) el "color:#fff" hace que los botones / paneles sean ilegibles

**Comment by saresq** [comment]
Tampoco es solucionable agregandole una clase `Text-gray / text-verdin`  ya que el bg-primary tiene la declaracion !important

**Comment by diegoarduino** [comment]
Gracias por tu colaboración @levihernan. Esto ya fue fixeado.
