### ISSUE TITLE
Falta clase para color de texto negro

### ISSUE THREAD

**Issue by saresq** [argob/poncho#22]
Existiendo las clases `Text-Gray / text-muted` sería util en algunos casos tener la posibilidad de tener un `text-default` o `text-black` para poder dar color negro a un texto

**Comment by diegoarduino** [comment]
Hola @saresq gracias por tu colaboración. Ya lo corregimos
https://github.com/argob/poncho/commit/57b30c843d6df41622a48c49693e67ffdc4ca70b
