### ISSUE TITLE
Forms y inputs no se leen cuando están sobre background de color

### ISSUE THREAD

**Issue by levihernan** [argob/poncho#26]
bg-success trae consigo text: #fff, y los inputs y las forms no tienen una corrección de color por lo que el texto queda blanco sobre blanco

**Comment by saresq** [comment]
+1

**Comment by diegoarduino** [comment]
Gracias por tu colaboración @levihernan. 
Esto ya fue fixeado aca https://github.com/argob/poncho/issues/29
