### ISSUE TITLE
bg classes usan color !important

### ISSUE THREAD

**Issue by levihernan** [argob/poncho#27]
Las background classes influyen el color del contenido pero overridean cualquier corrección hecha con las text classes. Está mal la jerarquía de reglas, no se puede poner texto negro en una sección con bg-primary

**Comment by diegoarduino** [comment]
Los helpers de texto no estan pensados para usar con fondo de color.
No estaria bien aplicado usar un bg-primary con un texto que no sea blanco.
Estamos trabajando en mejor la documentacion para explicar esto.
Muchas gracias!
