### ISSUE TITLE
input-sm font-size and height error

### ISSUE THREAD

**Issue by nicogol0** [argob/poncho#28]
Acutalmente, al utilizar la clase .input-sm en un elemento html select, por ejemplo:
```html
<label for="trimesters">Trimestre: </label>
<select class="form-control input-sm" id="trimesters" ng-model="bindingTrimester" convert-to-number>
    <option ng-repeat="t in trimesters" value="{{t}}">{{t}}</option>
</select>
```

El mismo no se muestra correctamente, cortando los números o letras de la opción seleccionada. A modo de ejemplo, mirar el segundo select box (Trimestre).
![poncho_bug_1](https://cloud.githubusercontent.com/assets/13947822/24512901/34829c36-1546-11e7-86db-0433af451d7c.png)

Si bien no sabemos si cumple con la especificacion de diseño de Poncho, una solución viable (la estamos utilizando por ahora) es agregar el siguiente código CSS (talvez [aquí](https://github.com/argob/poncho/blob/master/dist/css/poncho.css#L2963)):
```css
.input-sm, select.input-sm {
  height: 34px;
  line-height: 34px;
  font-size: 14px;
}
```
Quedando de la siguiente manera:
![poncho_bug_1_fix](https://cloud.githubusercontent.com/assets/13947822/24512902/34884f32-1546-11e7-967e-8222aec6746e.png)

Es correcto solucionarlo de esta forma?

Muchas Gracias!

**Comment by diegoarduino** [comment]
Muchas gracias por tu comentario, este issue ya fue fixeado aquí https://github.com/argob/poncho/commit/0a3c118ae0bda7916eb159aa7e34c41122cc2431
