### ISSUE TITLE
bg-classes usan color !important

### ISSUE THREAD

**Issue by levihernan** [argob/poncho#29]
Los background clases usan color de texto que overridean cualquier otra definición. 
No se pueden utilizar paneles, tablas, atajos o botones porque son blancos y su texto es blanco. (ver ejemplos)
No se pueden poner formularios porque cuando se llenan se escriben en blanco.
Sería util sumar la funcionalidad para que se pueda crear esto sin necesidad de clases extra:
![image](https://cloud.githubusercontent.com/assets/2326722/26328091/0f9cc40e-3f18-11e7-9b8c-8cf0f5e55bb5.png)
![image](https://cloud.githubusercontent.com/assets/2326722/26328155/3bc01a0e-3f18-11e7-9db3-7bdccfc9c56b.png)

**Comment by diegoarduino** [comment]
Gracias por tu colaboración @levihernan. Ya podrías poder usar esos componentes sobre contenedores con background class
