### ISSUE TITLE
Colores de fondo

### ISSUE THREAD

**Issue by martinszy** [argob/poncho#3]
En la documentación la sección colores de fondo está vacía:
https://argob.github.io/poncho/docs/#components

Sugiero eliminarla o poner algo de contenido.
¿El gobierno tendrá una paleta fija, manual de marca, algo así?

**Comment by julianrod** [comment]
El gobierno tiene un manual de marca y una paleta de colores. La que nosotros estamos produciendo es una ligera variación que funciona mejor en web. Considerá este lanzamiento un pre-alpha si se quiere... sabemos que falta corregir un montón de cosas. Abrazo

**Comment by martinszy** [comment]
Gracias por contestar. Ese manual de marca y paleta de colores aplica sólo a presidencia o a toda la administración nacional?
Tenés el enlace?

Más allá de esto, el item de colores de fondo sigue vacío y habría que eliminarlo o completarlo.
Gracias.

**Comment by julianrod** [comment]
El manual de marca no está subido a ningún lado todavía y no lo manejamos desde nuestra área.
Las correcciones que hay que hacer las estaremos haciendo pronto porque ya las teníamos identificada. Gracias

**Comment by Jinik** [comment]
@martinszy como bien comentaste, en la primera versión que publicamos había un error en el código y no se estaban viendo los elementos. Ya lo modificamos para que se vean bien.

Y como bien comentó @julianrod, estamos en desarrollo de la documentación y puede haber errores que vamos a estar corrigiendo, o mejoras que vamos a incorporar.

Gracias!

**Comment by martinszy** [comment]
Ahora aparece, veo otros errores pero serán otros issues.
Buenisimo que lo sigan mejorando. Abrazo!
