### ISSUE TITLE
Error en Identidad/Iconos (icono-arg-camion-sisterna)

### ISSUE THREAD

**Issue by kity-linuxero** [argob/poncho#304]
Hay un error en la identificación de Identidad/Íconos en 

![imagen](https://github.com/argob/poncho/assets/14118225/7b49e56a-e71f-4f68-a8c9-347daeee1cef)

La misma debería ser **camion-cisterna**.

**Comment by agustinbouillet** [comment]
¡¡Gracias por reportar el error!! El cambio se hará efectivo en el próximo _deploy_

¡Gracias nuevamente!  💯
