### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by FlorenciaP** [argob/poncho#32]
Hola.
Entre los componentes no encuentro un wizard para una tarea que requiere varios pasos. Por favor, necesitaría saber si tienen definido algún estándar.
Gracias y saludos,
Florencia.

**Comment by Roccella** [comment]
Seguramente ya lo hayas resuelto, pero en esta página vas a poder encontrar una barra de progreso (al principio) y botones de anterior y siguiente (al final) que es lo que estamos usando.

http://argob.github.io/poncho/plantillas/formularios/formulario_completo.html
