### ISSUE TITLE
Fechas

### ISSUE THREAD

**Issue by matiaet98** [argob/poncho#33]
Faltaria algun tipo de calendario para los inputs. Ya que se apoyaron en bootstrap, les recomiendo que vean este https://bootstrap-datepicker.readthedocs.io que se integra bastante bien.

**Comment by Roccella** [comment]
Estamos usando el tag date de html al final, que según el dispositivo o navegador cambia, pero es lo más estándard y accesible. Lo podés ver acá:
http://argob.github.io/poncho/plantillas/formularios/formulario_completo.html

Si llegás a ver que tiene errores podés reabrir el issue. Gracias.
