### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Sophivorus** [argob/poncho#34]
¿Sería conveniente proveer una URL para que los distintos sitios que utilicen Poncho puedan linkear, en vez de bajar su propia copia de Poncho? Es decir, conceptualmente sería proveer un CDN, pero no tiene por qué ser algo complicado. Para empezar, puede ser tan simple como poner Poncho en argentina.gob.ar/poncho.css y empezar a recomendar que se cargue Poncho desde ahí. Las ventajas serían:

* Si se hace una actualización o mejora a Poncho, todos los sitios que lo utilizan la tendrían inmediatamente.
* Los navegadores almacenarían el CSS en su cache, de modo que al entrar a otro sitio del gobierno que también utilice Poncho (y también lo carguen desde el CDN) no tendrían que volver a descargarlo.
* Sería fácil rastrear cuántos y cuáles sitios utilizan Poncho (desde el CDN).
* Instalar Poncho sería todavía más fácil de lo que es ahora.

**Comment by fernet0** [comment]
+1
Arsat tiene mirrors de CentOS, Debian y Apache que andan muy bien. Estaría bueno que la CDN este ahí.

**Comment by CesarD** [comment]
No del todo de acuerdo:
> Si se hace una actualización o mejora a Poncho, todos los sitios que lo utilizan la tendrían inmediatamente

Puede comprometer el diseño que alguien haya hecho basado en una version si en la actual ingresaron algun "breaking change" o algun otro detalle sobre el que se basó el diseño. Si el desarrollador no se da cuenta de manera explícita y está fuera de su control, puede resultar problemático.

> Los navegadores almacenarían el CSS en su cache, de modo que al entrar a otro sitio del gobierno que también utilice Poncho (y también lo carguen desde el CDN) no tendrían que volver a descargarlo.

Sin un número de versión en la url, el navegador va a dejar cacheada la misma version hasta que el usuario refresque cache (ctrl-f5) o lo limpie. Y si se implementa la versión en la url, se elimina el punto anterior.

Sería mucho mas conveniente la creación de un paquete npm, que le ofrece al desarrollador un control más preciso de la versión que quiere tener instalada y se integra con prácticamente cualquier entorno de desarrollo actual.
El cacheado y "cache busting" ante cambios de versiones correría por cuenta de la aplicación y la tecnología sobre la que esté desarrollada.

**Comment by Jinik** [comment]
Sí tenemos planificado implementar Poncho en un CDN propio, al igual que los assets necesarios en general, para facilitar el uso y aprovechar las ventajas de el cache. Además de aliviar la carga en la infraestructura de Argentina.gob.ar por archivos estáticos.

Concuerdo con que la ruta debería respetar las versiones (por lo menos las mayores) para evitar cambiar algo que genere problemas. De la misma forma no es aconsejable usar el link al de argentina.gob.ar porque con algún deploy podría cambiar la ruta o romper algo.

Dejo el issue abierto como mejora hasta lo que implementemos.
Gracias a todos por aportar!

**Comment by Roccella** [comment]
Buenas, después de muchas idas y vueltas discontinuamos la idea del CDN por cuestiones de inestabilidad de los servidores propuestos, que no pueden garantizar un uptime apropiado para operar como CDN.
