### ISSUE TITLE
Hexadecimal erróneo

### ISSUE THREAD

**Issue by dgmaggio** [argob/poncho#341]
En https://argob.github.io/poncho/identidad/colores/ el hexadecimal del azul principal es incorrecto (supongo que quedó el celeste que se utlizaba antes)

![image](https://github.com/argob/poncho/assets/63625613/010686d7-d470-46a8-9ba1-6be1edffa707)

**Comment by mpayeras** [comment]
Ya está actualizado el código del color. Gracias por el aviso.
