### ISSUE TITLE
Soporte para Bootstrap 4

### ISSUE THREAD

**Issue by cdmoro** [argob/poncho#35]
La versión de Bootstrap 4 ya dejó de ser beta. Estaría bueno que exista un branch donde se vaya adaptando Poncho a la nueva versión de Bootstrap.
Si se necesita colaboración, me ofrezco para ir actualizando el estilo.

¡Saludos!

**Comment by CesarD** [comment]
> La versión de Bootstrap 4 ya dejó de ser beta.

Si? 
https://github.com/twbs/bootstrap/releases
Parece que todavía no...

**Comment by cdmoro** [comment]
Es verdad, me dejé llevar por la emoción :smile: 
De todas formas, mi oferta de colaboración sigue en pie.

¡Saludos!

**Comment by Jinik** [comment]
Si bien Bootstrap 4 tiene muchas mejoras en general y hasta lógicas de componentes muy parecidas a las que tenemos como patrones en Poncho (las tarjetas por ejemplo) no tenemos planeado hacer una migración de versión. 

Nuestro enfoque hoy es hacer pruebas con usuarios para mejorar la usabilidad y accesibilidad de Poncho y las plataformas que construimos en el Estado. Es importante pensar primero en cómo impacta lo que hacemos en los ciudadanos y colaborar entre todos en mejorar Poncho en ese sentido.

Seguramente en el largo plazo tenga sentido, pero no es algo que vayamos a avanzar ahora.
Gracias por el aporte!

**Comment by arehot** [comment]
Estimados, necesito ayuda, estoy comenzando a ussr BootStrap, y baje la version 4, estoy haciendo un simple formaulario en donde ingreso las credenciales de acceso, pero no logro centrar los FORM que definí... Les muestro el codigo:

	<div class="my-content">
		<div class="container">

			<div class="row">
				<div class="col-sm-12">
					<h1>Control de Horas Trabajadas</h1>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-4 col-sm-offset-4 myform-cont">
					<form role="form" method="POST" action="login.php" class="">
						<div class="form-group">
							<input type="text" name="usuario" class="form-control" placeholder="Usuario" class="form-control" id="form-usuario"><br />
						</div>
						<div class="form-group">
							<input type="text" name="clave" class="form-control" placeholder="Contraseña" class="form-control" id="form-clave"><br />
						</div>
						<div class="form-group">
							<input type="submit" name="ingresar" class="btn btn-warning" value="Ingresar"><br />
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

Además les mando el pantallazo del resultado en donde veran que solo esta centrado el titulo, pero nos los FORM. Si alguien me puede decir que estoy haciebdo mal, se lo agracedería mucho...

Saludos...

![login](https://user-images.githubusercontent.com/35771224/35337923-39a1a094-00fb-11e8-9128-76a9cd306ff4.png)
