### ISSUE TITLE
Incorporar nuevos íconos

### ISSUE THREAD

**Issue by prensambiente** [argob/poncho#37]
Buenos días:
El día de ayer generé un pull request sin darme cuenta que antes había que generar un issue.
En fin, tal como explico en el pull request mi pedido radica en una necesidad que tenemos desde la oficina de prensa de la Secretaría de Ambiente y Ordenamiento Territorial del Gobierno de Mendoza. El asunto es simple, queremos ampliar y adecuar los íconos que están actualmente en el proyecto poncho y así poder utilizarlos en nuestra web. Yo soy diseñador gráfico y formo parte de dicho equipo de prensa.
Espero que puedan atender nuestro reclamo, para este caso en concreto, como para futuras sugerencias.
Muchas gracias. Saludos!

**Comment by Roccella** [comment]
Lo resolvimos con Gabriel Roatta por otra vía.
