### ISSUE TITLE
Consulta sobre la Disponibilidad del Manual de Marca de Presidencia y Ministerios

### ISSUE THREAD

**Issue by elsacherito** [argob/poncho#374]
Hola, quería consultar si existe y está disponible para compartir el Manual de Marca de Presidencia y Ministerios y otras dependencias. Agradecería cualquier ayuda o dirección para encontrar este recurso. Saludos

**Comment by agustinbouillet** [comment]
Hola Elsacherito. Hay un manual de marca. No está terminado aun. Escribime a bouilleta@jefatura.gob.ar y te envío una copia actualizada. 

Saludos
