### ISSUE TITLE
Agregar font-awesome a la guía de dependencias

### ISSUE THREAD

**Issue by devarg** [argob/poncho#38]
Estoy siguiendo la guía de integración de poncho para ver si lo usamos en un proyecto y encontramos que no especifica font-awesome como requerida aunque despues hace referencia a la misma. Estaría bueno que se agregue para que los que lo implementan, sepan que es requerida de hecho sino no funciona.

 Y las distintas maneras de integrarla, siendo una usandola desde el cdn

```
<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
```

ó para los ng-friends que no quieren cdn o por que estan atrás de un firewall pueden agregarlo en el **angular-cli.json**

```
...,
 "styles": [
        ...,
        "../node_modules/argob-poncho/dist/css/roboto-fontface.css",
        "../node_modules/argob-poncho/dist/css/poncho.min.css",
        "../node_modules/font-awesome/css/font-awesome.min.css"
      ],
...
```

Saludos

**Comment by Roccella** [comment]
Buenas, esta semana sumamos la explicación de cómo usar poncho en la página de inicio de la documentación http://argob.github.io/poncho/

Fijate si te sirve, y si no quedo atento a sugerencias para que lo mejoremos. Por ejemplo eso de angular que mencionás. Saludos!

**Comment by YoelSolca** [comment]
Buenas alguno sabe como puedo usar los iconos en Angular ya que no me los toma. Gracias
