### ISSUE TITLE
Navbar roto

### ISSUE THREAD

**Issue by Sophivorus** [argob/poncho#41]
Hola! Estoy experimentando con Poncho y no logro que la navigation bar se vea bien. Creé un HTML ultra minimalista, incluí poncho.css y roboto-fontface.css como se explica en el README de este repo, y copié en el body del HTML el código del navigation bar que hay en https://argob.github.io/poncho/docs/componentes.html#navbar. Les adjunto una screen de cómo se ve y también un [zip](https://github.com/argob/poncho/files/1975445/test.zip) para que puedan reproducir el bug ustedes mismos.

![screen shot 2018-05-04 at 3 07 02 pm](https://user-images.githubusercontent.com/3542266/39644735-efdf72be-4fac-11e8-833d-c9b8848efe36.png)

**Comment by lautaroaimar** [comment]
Hola, estoy en el celu y no puedo bajar tu zip, pero la documentación de poncho especifica que jQuery y bootstrap son dependencias directas del framework (además de roboto), y por lo que veo en la captura.. tiene aspecto que te faltan dependencias.

**Comment by devarg** [comment]
@Sophivorus si el issue esta resuelto cerralo nomás

**Comment by Sophivorus** [comment]
No está resuelto! Adjunté un zip con todo lo necesario para reproducirlo, e intenté resolver el issue yo mismo más de una vez pero no pude.

**Comment by Sophivorus** [comment]
Bueno, tras mucha prueba y error lo resolví. El problema era que Poncho requiere Bootstrap 3.3.7 y no funciona (o al menos el navbar no funciona) con la versión más reciente 4.0
