### ISSUE TITLE
Compatibilidad con Bootstrap 4.0

### ISSUE THREAD

**Issue by Sophivorus** [argob/poncho#42]
Como se explica en el issue #41, el navbar (y probablemente otros elementos) no funcionan bien con la versión más reciente de Bootstrap 4.0.

**Comment by CesarD** [comment]
Es una versión nueva, por lo tanto es lógico que contenga _breaking changes_.
Todo el sistema de grilla cambia por completo en BS 4, por lo tanto si Poncho se modifica para ser compatible con esta nueva versión, no podrá ser compatible con la anterior (salvo que se armen archivos separados con soporte para cada versión de BS).

**Comment by devarg** [comment]
+1

**Comment by cdmoro** [comment]
+1

**Comment by Roccella** [comment]
Buenas, les comparto la primer versión de Poncho para Bootstrap 4

http://argob.github.io/poncho/bs4/index.html

Lo que incluye esta versión es cambios en: 
- Colores accesibles de Poncho
- Tipografía Roboto
- Estilos de botones y enlaces

Si ven el código del archivo van a ver que lo que necesitan incluír son estos archivos en el head de la página:

<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
<link href="bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../node_modules/argob-poncho/dist/icono-arg.css">

Y estos archivos antes del final del body:

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="bootstrap.min.js"></script>

Eso es lo mínimo para que funcione. Todavía no hay un listado de componentes por los que pueden usar los de Bootstrap 4 que estarían bien. Lo mismo si necesitan sumar javascripts de componentes extra.

En la página de prueba hay un ejemplo de listado de uno de los componentes más usados que son las tarjetas que son todas clickeables, ya puestas en un formato que se ve bien en responsive.

La forma de usar los componentes es similar a la de la versión de Poncho para Bootstrap 3: http://argob.github.io/poncho/

Es decir que por ejemplo si bien existen los estilos para usar textos o botones amarillos, en Poncho no los usamos.

Saludos!
