### ISSUE TITLE
Cómo contribuir

### ISSUE THREAD

**Issue by Sophivorus** [argob/poncho#43]
Quisiera hacer algunas contribuciones (menores) al README de este repo. Pero no estoy seguro si el repo que hay acá es el principal o si es un mirror de un repo privado. Si mando contribuciones acá, ¿se van a mergear o se van a perder la próxima vez que actualicen este repo con la versión más reciente del repo privado?

**Comment by jfgabriel** [comment]
+1

**Comment by fedomkf1** [comment]
Este repo es el principal que se utiliza para la versión oficial de drupar. 
Asique todas las contribuciones son bienvenidas.
