### ISSUE TITLE
Template para Wordpress

### ISSUE THREAD

**Issue by jfgabriel** [argob/poncho#47]
Buenos días a todos!
Estoy armando un template para Wordpress basado en Poncho, pero me gustaría saber si alguien ya armó un proyecto así o conoce alguno.
He visto los sitios que usan poncho usan Drupal, pero tenemos un requerimiento de usar Wordpress.

Gracias!

**Comment by saresq** [comment]
Bueen dia!

Con el equipo de desarrolladores del Ministerio de Producción tenemos un template de Poncho en WordPress, si queres nos ponemos en contacto!

**Comment by lautaroaimar** [comment]
Hola, a mí me interesa el template.
Gracias de antemano.

**Comment by changeme** [comment]
Buenas. Lo mismo por acá.
Estaría bueno poder implementarlo en un proyecto interno

**Comment by pcerdeira** [comment]
Hola! Está disponible el template para wordpress?

**Comment by jfgabriel** [comment]
> Bueen dia!
> 
> Con el equipo de desarrolladores del Ministerio de Producción tenemos un template de Poncho en WordPress, si queres nos ponemos en contacto!

Si, genial. Vi muy tarde el mensaje. ¿Cómo hacemos para compartirlo?

**Comment by changeme** [comment]
> > Bueen dia!
> > Con el equipo de desarrolladores del Ministerio de Producción tenemos un template de Poncho en WordPress, si queres nos ponemos en contacto!
> 
> Si, genial. Vi muy tarde el mensaje. ¿Cómo hacemos para compartirlo?

Crea un nuevo repositorio y subilo directamente.

**Comment by hernanjh** [comment]
> Bueen dia!
> 
> Con el equipo de desarrolladores del Ministerio de Producción tenemos un template de Poncho en WordPress, si queres nos ponemos en contacto!

buenas, nos podrías compartir el template para wordpress.

gracias

**Comment by lautaroaimar** [comment]
> 
> 
> > Bueen dia!
> > Con el equipo de desarrolladores del Ministerio de Producción tenemos un template de Poncho en WordPress, si queres nos ponemos en contacto!
> 
> buenas, nos podrías compartir el template para wordpress.
> 
> gracias

Me sumo al pedido

**Comment by matudelatower** [comment]
Yo había hecho una adaptación, de hecho está en uso actualmente 

https://github.com/matudelatower/wp-poncho

https://hcdposadas.gob.ar/

**Comment by changeme** [comment]
> Yo había hecho una adaptación, de hecho está en uso actualmente
> 
> https://github.com/matudelatower/wp-poncho
> 
> https://hcdposadas.gob.ar/

Voy corriendo a probarlo. Gracias!

**Comment by Roccella** [comment]
Buenas, si les parece podemos mencionar a este repositorio dentro de la documentación de Github. Dando crédito a Matu. Cierro el issue pero cualquier cosa me contactan.
