### ISSUE TITLE
Visualización incorrecta letra g (variante itálica en minúscula)

### ISSUE THREAD

**Issue by fedee13** [argob/poncho#48]
Al escribir la letra 'g' con la fuente Roboto en itálica, se visualiza incorrectamente el glypho, en el ojo de la 'g'

**Comment by Roccella** [comment]
Buenas, ahora estamos tomando la fuente Roboto directo del CDN de google, por lo que no sucede más en los productos que ya tienen implementado este cambio (no todos lo están al día de hoy, pero estamos trabajando para eso). Saludos y gracias!
