### ISSUE TITLE
Poncho (tema) Theme y Drupal 10

### ISSUE THREAD

**Issue by Gabi-Nes** [argob/poncho#492]
Hola, quería saber si existe algún tema (theme) armado de "Poncho", para subir directamente a Drupal y trabajarlo desde ahí. 
Si es así, ¿está disponible para Drupal 10 o para cual es la versión de Drupal última disponible?
Si no hay un theme "Poncho", ¿cómo hago desarrollar desde cero un sitio Web para un organismo del Estado con Drupal?, ¿Debo usar puro HTML, o qué tema, módulo, etc. debo instalar? ¿Cuál es la última versión que puedo usar de Drupal?
Desde ya muchas gracias
Saludos

**Comment by jmdocile** [comment]
Por el momento no contamos con un tema (theme) armado de Poncho para CMS (Drupal, Wordpress, etc.). Esto se debe que por la normativa vigente, las jurisdicciones del estado nacional, no pueden contar con un CMS distinto a Argentina.gob.ar
Si lo que se está desarrollando es un sistema con autenticación, el mismo debe contar con Poncho y está disponible como un framework (CSS y JS).
Actualmente sigue utilizando la base de Bootstrap 3.4.
Cualquier consulta, no dudes en contactarnos. 
https://www.argentina.gob.ar/contenidosdigitales
