### ISSUE TITLE
Template Poncho para Joomla 3.x

### ISSUE THREAD

**Issue by jap400** [argob/poncho#50]
Estoy probando de adaptar Poncho a un template limpio de Joomla 3.x,  Alguno tiene alguna experiencia en eso?

**Comment by fedomkf1** [comment]
Hola, 

Tengo un poco de experiencia en poncho y en joomla, avisame que necesitas y lo hacemos funcionar.

**Comment by jap400** [comment]
qué bueno! opté por un framework bastante completo, que es el T3 (de joomlart) y un template limpio basado en t3 y bootstrap. **t3_bs3_blank** esteticamente le pude incorporar un Poncho personalizado, pero aun me quedan algunas funcionalidades no resuelstas, por ejemplo, ponchorizar la vista de las noticias (que es totalmente dinámica) creo que tengo que toquetear el PHP...

ver : [www.idera.gob.ar](https://idera.gob.ar)

**Comment by jap400** [comment]
Adapté bajo el framework T3 (de joomlart) el template bootstrap llamado "t3_bs3_blank" al cual incorporé esteticamente el Poncho, sin mayor dificultad. Pero aun me quedan cosas pendientes, como por ejemplo mostrar el muro de noticias "ponchorizado"... (pero es dinámico, y no descubro como toma los estilos)... ver: [www.idera.gob.ar](https://www.idera.gob.ar)

**Comment by Roccella** [comment]
Buenas, la veo muy bien a esa implementación, si te parece pasame el link del repositorio por mail y lo subimos a la documentación junto con el theme de wordpress que hizo otra persona. Cierro el issue pero cualquier cosa contactame a proccella@modernizacion.gob.ar

Gracias!
