### ISSUE TITLE
Mejorar documentación

### ISSUE THREAD

**Issue by vo-aaip** [argob/poncho#52]
Chicos les dejo unas sugerencias

0) Estaria bueno que pongan un "como empezar", o un "necesitas incluir en tus paginas estas librerias" asi la gente sabe que tiene que descargar bootstrap y las datatables en caso que lo necesiten, porque si solo se bajan poncho no les va a andar nada.

1) Patrones de uso: es util pero no tiene el codigo html . Son capturas en imagen JPG. Seria útil que lo pongan asi se puede copiar y pegar para obtener el estilo deseado.

2) La docu del 2015 (https://argob.github.io/poncho/2015/documentacion.html ) cuenta con mas ejemplos utiles que la nueva docu , podrian incorporarlos.

**Comment by Roccella** [comment]
Buenas, pueden escribirme a proccella@modernizacion.gob.ar ?

Tomo los 3 comentarios que mencionan, pero me gustaría hablar o reunirme con ustedes para ir un poco más allá.

Saludos!

**Comment by Roccella** [comment]
Buenas, nos reunimos con Verónica. De este issue resolvimos:

1. Cómo instalar poncho, ahora aparece en la página de inicio http://argob.github.io/poncho/
2. Patrones de uso fue reemplazado por la sección de Plantillas
3. Estamos de a poco terminando de subir todos los componentes que estaban en la documentación nueva, como componentes y plantillas

Saludos!
