### ISSUE TITLE
algún plan para migrar poncho a bs 4 (o mejor aún tailwind css?)

### ISSUE THREAD

**Issue by opensas** [argob/poncho#54]
vi este issue: https://github.com/argob/poncho/issues/42 pero no dice nada acerca de algún plan para migrar poncho a bs4

si la migración es muy costosa sería bueno que puedan evaluar otras alternativas de tipo utility css, como tailwindcss

**Comment by Roccella** [comment]
Buenas, les comparto la primer versión de Poncho para Bootstrap 4

http://argob.github.io/poncho/bs4/index.html

Lo que incluye esta versión es cambios en: 
- Colores accesibles de Poncho
- Tipografía Roboto
- Estilos de botones y enlaces

Si ven el código del archivo van a ver que lo que necesitan incluír son estos archivos en el head de la página:

<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
<link href="bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../node_modules/argob-poncho/dist/icono-arg.css">

Y estos archivos antes del final del body:

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="bootstrap.min.js"></script>

Eso es lo mínimo para que funcione. Todavía no hay un listado de componentes por los que pueden usar los de Bootstrap 4 que estarían bien. Lo mismo si necesitan sumar javascripts de componentes extra.

En la página de prueba hay un ejemplo de listado de uno de los componentes más usados que son las tarjetas que son todas clickeables, ya puestas en un formato que se ve bien en responsive.

La forma de usar los componentes es similar a la de la versión de Poncho para Bootstrap 3: http://argob.github.io/poncho/

Es decir que por ejemplo si bien existen los estilos para usar textos o botones amarillos, en Poncho no los usamos.

Saludos!

**Comment by opensas** [comment]
Felicitaciones!!!

Van a armar algo similar al sitio https://argob.github.io/poncho/ para BS4? Es muy útil tener ejemplos de uso para copiar y pegar...

Un detalle, en la página https://argob.github.io/poncho/bs4/index.html la barra superior no es responsive

**Comment by Roccella** [comment]
Gracias! Ahora corregimos la barra superior.

También tenemos pensado en principio hacer una página con varios componentes listos para usar, y luego una documentación completa como la actual de Poncho para BS3.

**Comment by nicxes** [comment]
Hola @Roccella, donde podría encontrar los archivos scss, de la versión de boostrap v4?

**Comment by Roccella** [comment]
Lo podés ver acá https://github.com/argob/poncho/tree/gh-pages/bs4

**Comment by Jonyx4** [comment]
Puede ser que la URL No funciona mas? la de BS4
