### ISSUE TITLE
error en archivo icono-arg.css - no aparecen los iconos

### ISSUE THREAD

**Issue by opensas** [argob/poncho#55]
Cuando inluyo el css desde:

```html
<link rel="stylesheet" href="https://qa-poncho.argentina.gob.ar/dist/icono-arg.css">
```

el ícono se ve así

![image](https://user-images.githubusercontent.com/481687/66598767-2623e400-eb78-11e9-85a2-f0f95117e549.png)

cuando lo incluyo desde

```html
  <link rel="stylesheet" href="https://argob.github.io/poncho/node_modules/argob-poncho/dist/icono-arg.css">
```

funciona bien

**Comment by opensas** [comment]
Por lo que veo a simple vista, commitearon un archivo con conflictos:

![image](https://user-images.githubusercontent.com/481687/66599089-dbef3280-eb78-11e9-9071-b669db45c8b6.png)

**Comment by Roccella** [comment]
Buenas, dejamos de usar el ambiente de qa-poncho. Y todavía estamos mejorando la parte de "cómo instalar poncho", pero la idea es que se use de forma local (en su momento intentamos construír un CDN pero no sucedió).

Por las dudas te consulto, lo viste en alguna página de documentación actualizada? Así saco el uso de qa-poncho de todos lados porque en cualquier momento bajamos ese servidor.

Gracias y saludos.

**Comment by opensas** [comment]
Honestamente no recuerdo de dónde sacamos ese link, es una copia de alguna aplicación anterior.

Como crítica constructiva, no queda claro cómo instalar poncho, creo que sería necesario un ejemplo de uso claro y completo.

En la página http://argob.github.io/poncho/ no dice cómo instalarlo y te manda a descargar los arhcivos de github, y en el readme del repo en github te manda de vuelta a http://argob.github.io/poncho

Tampoco me queda claro si la parte de releases, los archivos zip (https://github.com/argob/poncho/archive/v0.3.3.zip) tienen todos los archivos necesarios para utilizar poncho ni qué es lo que habría que incluir (no veo, por ejemplo, el archivo icono-arg.css que están usando desde view-source:http://argob.github.io/poncho/estilos/iconos/, linea 100)

Lo que suelo hacer es ver el source de los templates de ejemplo que publican en http://argob.github.io/poncho (ya que allí encuentro la funcionalidad que necesito y veo que está funcionando) y me bajo los archivo locales, o a veces, como seguramente pasó en este caso, meto el mismo url de un ejemplo que encontré funcionando)

Viendo el fuente veo que suelen incluir los archivos desde la carpeta node_modules, eso significa que la manera recomendada de instalar poncho es a través de npm?

Muchas gracias por la respuesta y los felicito por el trabajo que están haciendo, mantener y actualizar esta librería de estilos seguramente no es tarea fácil!

**Comment by Roccella** [comment]
Gracias por el aliento!

Esta semana incluímos el "cómo instalar poncho" en la página de inicio http://argob.github.io/poncho/ donde especificamos qué librerías usar directo de CDNs y cuáles son las de poncho a usar de forma local (dado que cancelamos lo del CDN de qa-poncho)

Lo de releases donde lo viste? Porque también actualizamos el branch master de poncho con lo mismo de "cómo instalar poncho", pero capaz quedó algo colgado.

Desde ya mil gracias por la colaboración!

**Comment by opensas** [comment]
Los releases los bajo de la opcion release de github: https://github.com/argob/poncho/releases

Y muy buenas las instrucciones para instalar poncho!

**Comment by Roccella** [comment]
Excelente, gracias. Por las dudas te comento que hicimos una primer versión de Poncho para Bootstrap 4, te comento:

Buenas, les comparto la primer versión de Poncho para Bootstrap 4

http://argob.github.io/poncho/bs4/index.html

Lo que incluye esta versión es cambios en: 
- Colores accesibles de Poncho
- Tipografía Roboto
- Estilos de botones y enlaces

Si ven el código del archivo van a ver que lo que necesitan incluír son estos archivos en el head de la página:

<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
<link href="bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../node_modules/argob-poncho/dist/icono-arg.css">

Y estos archivos antes del final del body:

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="bootstrap.min.js"></script>

Eso es lo mínimo para que funcione. Todavía no hay un listado de componentes por los que pueden usar los de Bootstrap 4 que estarían bien. Lo mismo si necesitan sumar javascripts de componentes extra.

En la página de prueba hay un ejemplo de listado de uno de los componentes más usados que son las tarjetas que son todas clickeables, ya puestas en un formato que se ve bien en responsive.

La forma de usar los componentes es similar a la de la versión de Poncho para Bootstrap 3: http://argob.github.io/poncho/

Es decir que por ejemplo si bien existen los estilos para usar textos o botones amarillos, en Poncho no los usamos.

Saludos!
