### ISSUE TITLE
Se incluyen archivos .DS_Store

### ISSUE THREAD

**Issue by rgorosito** [argob/poncho#58]
El archivo .gitignore solo hace referencias a los archivos en la raíz. Hice el PR https://github.com/argob/poncho/pull/57 para el fix el cual ahora tiene conflictos. Podría hacer otro pero posiblemente vuelva a tener conflictos al continuar haciendo modificaciones sin revisar el PR.

**Comment by Roccella** [comment]
Ahí se agregó un gitignore de .ds_store al directorio /dist que no lo tenía. Gracias!
