### ISSUE TITLE
LOS ÍCONOS NO CARGAN 

### ISSUE THREAD

**Issue by santasma** [argob/poncho#71]
Hola
Hasta hace unos días el listado de íconos de Argentina funcionaba perfectamente pero hoy se queda en loading.
Porfa agradezco que solucionen este inconveniente.
Muchas Gracias

https://argob.github.io/poncho/identidad/iconos/

**Comment by jmdocile** [comment]
Si, se están tomando los íconos desde una planilla de Google Spreasheet. Deprecaron la API.

**Comment by jmdocile** [comment]
Solucionado. Gracias.
