### ISSUE TITLE
!Important Declarations

### ISSUE THREAD

**Issue by jbrizio** [argob/poncho#8]
Estimados,

Realizando un review del código CSS ```poncho.css``` he encontrado en repetidas oportunidades el uso de la declarativa ```!important```. ¿Es necesario hacer uso de esta declarativa tantas veces? Extendiendo la especifidad podría evitarse esto.

Lectura recomendada:
https://www.smashingmagazine.com/2010/11/the-important-css-declaration-how-and-when-to-use-it/#never

**Comment by Jinik** [comment]
Hola @jbrizio, si bien es cierto lo que comentas, hay que tener en cuenta que la gran mayoría de los `!important` están en clases que funcionan de helper para modificar cualquier elemento que sea necesario hacerlo, por lo que es difícil hacerlo desde el selector.

De todas formas hay varios componentes que lo tienen sin necesidad y lo vamos a estar resolviendo pronto.

Muchas gracias por el aporte!
