### ISSUE TITLE
Botones de Checkbox

### ISSUE THREAD

**Issue by sebastianarca** [argob/poncho#80]
Les planteo un agregado que me seria de mucha utilidad.

Agregar formas de graficar opciones para formulario input del tipo **Checkbox** y **Radio** o en caso de estar disponible agregarlo en la documentacion, con el proposito de unificar las interfaces visuales para todos los organismos publicos.

Saludos !

**Comment by jmdocile** [comment]
Sebastian, como estas? 

Algo de esto es lo que estas buscando? 

https://argob.github.io/poncho/plantillas/formularios/formulario_completo.html

Si no lo es, te pido por favor, si podes ser mas especifico.

**Comment by sebastianarca** [comment]
@jmdocile Ese formulario lo vi a posterior y de hecho me fue de mucha utilidad. 
Los checkbox e radio que estan en el formulario son utiles para seleccion de datos puntuales, pero poco utiles para cuando se trata de marcar otro tipo de opciones que deben ser visualmente mas llamativas.
Por ejemplo en caso de dar la opcion para enviar una copia por email.

Puntualmente a lo que me refiero es a algo como lo que esta presente en Bootstrap 5 https://getbootstrap.com/docs/5.1/forms/checks-radios/#switches 
O como lo resolvi de momento https://bootsnipp.com/snippets/xp0QM


Gracias por la respuesta, y disculpas por lo ambiguo del primer comentario.
